# An example where a conventional RNN fails, due to a lack of symmetry

In [1]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import sys
from os import path
from keras.utils.np_utils import to_categorical   

Using TensorFlow backend.


## Simulate Data
$m$ sequences each of length $\ell$ and binary class $y$.  
class $y\sim \text{Bernoulli}(0.5)$  

$$x=(x_1,\ldots, x_\ell)$$
$x_i \sim \text{Bernoulli}(0.5)$ (iid)
Falls $y_i=1$, setze
$$x[t..t+10) \leftarrow 1$$

In [2]:
ell = 100
m = 5000
siglen = 10
s=2 # alphabet size

In [3]:
np.random.seed(13)

# development test data
def simulate_data(m, t, oneHot=True, standardize=False):
    x = np.random.randint(2, size = m*ell).reshape(m, ell)
    y = np.random.randint(2, size = m)
    for i in range(m):
        if y[i]:
            x[i, t:t + siglen] = 1
    if oneHot:
        x = to_categorical(x, num_classes=2)
    if standardize: # is better for SimpleRNN, oneHot or not
        x = x - 0.5 # standardize
    return x, y

## Obtain the training set

In [4]:
regenerate = True
fname = "rnn-fail-data.npz"

if regenerate or not path.exists(fname):
    # simulate new data
    x, y = simulate_data(3, t=20)
    np.savez(fname, x=x, y=y)

In [5]:
npzfile = np.load(fname)
x = npzfile['x']
y = npzfile['y']
print ("y", y, "\nx", x.shape, x[0,0:10,:])

y [1 1 1] 
x (3, 100, 2) [[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]]


## Build the Model

In [6]:
from HMMCell import HMMCell, HMMLayer

In [7]:
seqLayer = HMMLayer(2, 11)
seqLayer(x)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-6.4724684e-04, -2.3025274e-04],
       [-2.2258759e-03, -8.3214045e-04],
       [-5.3644180e-05, -5.3048134e-06]], dtype=float32)>

In [8]:
def get_model(bidirectional = False, seqModelType = "SimpleRNN", RNNunits = 32):
    model = keras.Sequential()
    model.add(layers.InputLayer(input_shape=(None,s)))

    if seqModelType == "HMM":
        seqLayer = HMMLayer(5, 11)
    elif seqModelType == "LSTM":
        seqLayer = layers.LSTM(RNNunits)
    elif seqModelType == "GRU":
        seqLayer = layers.GRU(RNNunits)
    elif seqModelType == "SimpleRNN":
        seqLayer = layers.SimpleRNN(RNNunits)
    else:
        sys.exit("unknown sequence model type " + seqModelType)

    if bidirectional:
        seqLayer = layers.Bidirectional(seqLayer)
    
    model.add(seqLayer)
    model.add(layers.Dense(1))
    lr = 1e-3
    if seqModelType == "HMM":
        lr = 1e-2
    print (f"lr={lr}")
    model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate = lr),
                  loss = tf.keras.losses.BinaryCrossentropy(), metrics = ["accuracy"])
    return model

In [9]:
model = get_model(bidirectional = False, seqModelType = "SimpleRNN", RNNunits = 32)
model.summary()
model = get_model(bidirectional = False, seqModelType = "HMM")
model(x)
model.summary()
W = model.get_layer(index=0).C
W.print_pars()

lr=0.001
Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 32)                1120      
_________________________________________________________________
dense (Dense)                (None, 1)                 33        
Total params: 1,153
Trainable params: 1,153
Non-trainable params: 0
_________________________________________________________________
lr=0.01
Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
hmm_layer_1 (HMMLayer)       (None, 5)                 770       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 6         
Total params: 776
Trainable params: 776
Non-trainable params: 0
_________________________________________________________________
transition matric

## Ad hoc fixed prediction method
$$ \hat{y} = 1 :\Leftrightarrow \exists j: x[j..j+10) = 1$$

In [10]:
def adhoc_pred(x):
    x = np.squeeze(x+.5).astype('int')
    A = np.cumsum(x, axis=1)
    B = np.zeros_like(A)
    B[:,siglen:] = A[:,:-siglen]
    yhat = np.any(A-B >= siglen, axis=1).astype('int')
    return yhat

In [11]:
def adhoc_acc(x_test, y_test):
    yhat = adhoc_pred(x_test)
    correct = (yhat == y_test).astype('int')
    return correct.mean()

## Train the Model

In [12]:
from time import time

# ts = np.array(range(ell - 15, -1, -10))
ts = np.array(range(ell - 15, 39, -20))

len(ts)

3

In [13]:
num_reps = 1 # 30
num_epochs = 40
modelnames = ["HMM"] #"SimpleRNN", "LSTM", "GRU", "ad hoc"]
directions = [False] # , True] # bidirectional?
test_accs = { (name, direction) : np.empty((len(ts), num_reps)) for name in modelnames for direction in directions}

for modelname in modelnames:
    start_time = time()
    for direction in directions:
        print (modelname, "dir=", direction, "\t", end = "")
        for j in range(len(ts)):
            print (j, " ", end = "")
            t = ts[j]
            accs = test_accs[(modelname, direction)]
            for r in range(num_reps):
                accuracy = 0.0
                x_test, y_test = simulate_data(1000, t)
                if modelname == "ad hoc":
                    accuracy = adhoc_acc(x_test, y_test)
                else:
                    model = get_model(bidirectional = direction, seqModelType = modelname, RNNunits = 32)
                    x_train, y_train = simulate_data(m, t)
                    x_val, y_val = simulate_data(100, t)
                    model.get_layer(index=0).C.print_pars()
                    model.fit(x_train, y_train,
                          validation_data = (x_val, y_val), batch_size = 16, epochs = num_epochs,
                              verbose=1 if modelname=="HMM" else 0)
                    if modelname == "HMM":
                        # print transition and emission matrices
                        model.get_layer(index=0).C.print_pars()
                    results = model.evaluate(x_test, y_test, batch_size = 16, verbose=0)
                    # print ("j=", j, "\tt=", t, "\tr=", r, "\tresults=", results)
                    accuracy = results[1]
                accs[j, r] = accuracy
        print ("\n", accs)
    end_time = time()
    seconds_elapsed = end_time - start_time
    print ("time [s]:", seconds_elapsed)

HMM dir= False 	0  lr=0.01
transition matrices A:
 [[[0.08777 0.08829 0.0929  0.09484 0.09043 0.09016 0.08868 0.09495 0.09071 0.08881 0.09244]
  [0.08884 0.08776 0.09029 0.09153 0.0954  0.08845 0.09117 0.09226 0.09425 0.08797 0.09207]
  [0.09277 0.09031 0.09121 0.08736 0.08704 0.09122 0.09309 0.09214 0.09245 0.0941  0.08831]
  [0.08691 0.09233 0.09401 0.09425 0.0921  0.0916  0.08975 0.09313 0.08722 0.08611 0.09259]
  [0.09332 0.09205 0.09335 0.09036 0.08944 0.08985 0.08908 0.08967 0.0945  0.08861 0.08978]
  [0.09082 0.09263 0.08859 0.08668 0.08665 0.08852 0.09535 0.09109 0.09529 0.08923 0.09514]
  [0.09301 0.09085 0.0952  0.09096 0.09276 0.09402 0.09391 0.08652 0.08647 0.08975 0.08656]
  [0.09024 0.08794 0.09266 0.09186 0.09035 0.08954 0.09251 0.09401 0.09053 0.0929  0.08745]
  [0.0924  0.08584 0.09132 0.09322 0.09164 0.09356 0.09318 0.08839 0.08646 0.08956 0.09444]
  [0.08754 0.09259 0.09408 0.09028 0.09055 0.09175 0.09392 0.08953 0.08575 0.08944 0.09458]
  [0.09271 0.08966 0.09082 0.

KeyboardInterrupt: 

## Plot Results

In [ ]:
#  single plot
somemodelnames = ["HMM"] #["SimpleRNN", "LSTM", "GRU", "ad hoc"]
fig, ax = plt.subplots(1,2, figsize=(14, 5))
for j, direction in enumerate(directions):
    for i, model in enumerate(somemodelnames):
        avg_test_acc = np.mean(test_accs[(model, direction)], axis = 1)
        ax[j].plot(ts, avg_test_acc, 'o-', label = model)
    ax[j].set_title('Performance of established ' + ("bidirectional" if direction else "unidirectional") + " sequence models" )
    ax[j].set_xlabel("t")
    ax[j].set_ylabel("accuracy");
    ax[j].legend()
print ('Accuracy was averaged over ' + str(num_reps) + ' repetitions')
fig.savefig('failing1.pdf') 

In [ ]:
modelnames

In [ ]:
# one plot each
fig, ax = plt.subplots(len(modelnames), len(directions), squeeze=False, figsize=(25,20))
for i, model in enumerate(modelnames):
    for j, direction in enumerate(directions):
        avg_test_acc = np.mean(test_accs[(model, direction)], axis = 1)
        ax[i,j].plot(ts, avg_test_acc)
        ax[i,j].set_ylim([.45, 1])
        ax[i,j].set_title('Test accuracy of ' + model + ' model ' + ("(Bidirectional)" if direction else "") + ' averaged over ' + str(num_reps) + ' repetitions')
        ax[i,j].set_xlabel("t")
        ax[i,j].set_ylabel("accuracy");

In [ ]:
fig.savefig('failing.pdf') 