# HMM with TensorFlow

In [1]:
import tensorflow as tf
import numpy as np
import sys

## Weather HMM example
Das Wetter bei deinem Übersee-Chatfreund lässt sich durch eine Markowkette $X_1,X_2,\ldots$ mit
Zustandsraum $Q=\{\texttt{sun},\texttt{rain},\texttt{storm}\}$ und Übergangsmatrix
$$A=(A[r,s])_{\scriptsize r,s \in Q} = \begin{pmatrix}
0.7 & 0.2 & 0.1\\
0.3 & 0.5 & 0.2\\
0.2 & 0.6 & 0.2\\
\end{pmatrix}
$$
beschreiben (Reihen und Spalten in der Reihenfolge `sun`, `rain`, `storm`).

Dabei sei $X_i$ das Wetter am $i$-ten Tag und $X_1=\texttt{sun}$. Dein Freund verfolgt vom Wetter abhängig Aktivitäten entweder drinnen 
(`in`) oder draußen (`out`). Sei $\Sigma:=\{\texttt{in},\texttt{out}\}$. Folgende Matrix
beschreibe die vom Wetter abhängenden Wahrscheinlichkeiten (Wkeiten) der Aktivitäten
$$B=\big(B[q,s]\big)_{\scriptsize\begin{array}{l}q\in Q\\s\in \Sigma\end{array}} = \begin{pmatrix}
0.4 & 0.6 \\
0.8 & 0.2 \\
0.9 & 0.1 \\
\end{pmatrix}
.$$ 
Ablesebeispiel: Dein Freund bleibt mit Wkeit 0.9 drinnen, wenn es an dem Tag stürmt (Spalten in der Reihenfolge `in`, `out`).
Beantworte folgende Fragen für das durch $Q,\Sigma,A,B$ und $X_1$ gegebene Hidden-Markow-Modell.
Was ist die Wkeit 
$$P(Y_1=Y_2=Y_3=\texttt{in}),$$

dass dein Freund am allen drei Tagen drinnen bleibt?

![forward DP table](forwardManually.png)

**Solution: P(Y=y) = 0.1308**

## Specify the Model

### Example Model Parameters

In [2]:
n = 3 # number of states
s = 2 # emission alphabet size

In [3]:
A_init = np.array([[7, 2, 1], [3, 5, 2], [2, 6, 2]]) / 10.0
B_init = np.array([[4, 6], [8, 2], [9, 1]]) / 10.0
X1_dist = np.array([1., 0., 0.]) # starts with sun
n, s = B_init.shape # number of states, emission alphabet size
y = np.array([0, 0, 0]) # in, in, in

In [4]:
print("transitions:\n", A_init, "\nemissions:\n", B_init)

transitions:
 [[0.7 0.2 0.1]
 [0.3 0.5 0.2]
 [0.2 0.6 0.2]] 
emissions:
 [[0.4 0.6]
 [0.8 0.2]
 [0.9 0.1]]


#### Forward recursion
$$\alpha[i,q] = B[q, y[i]] \sum_{q'} \alpha[i-1, q'] \cdot A[q',q] $$

In [5]:
# tf variants of the transition and emission matrix
A = tf.Variable(A_init, trainable = True)
B = tf.Variable(B_init, trainable = True)

### Forward Variables and Algorithm
$$ \alpha(q,i) = \sum_{x_1,\ldots, x_{i-1}\in Q} P(x_1,\ldots, x_{i-1}, X_i=q, y_1,\ldots, y_i)$$
Initialization: 
$$ \alpha(q, 1) = \sum_{q\in Q} P(X_1 = q)\cdot B[q,y[0]]$$

In [6]:
def forward(y # observation sequence
           ):
    """ Forward Algorithm for Computing Sequence Likelihood """
    ell = y.shape[0]
    α = tf.Variable(np.zeros([ell, n]), trainable = False)
    
    # initialization
    α[0].assign(tf.multiply(B[:, y[0]], X1_dist))
    
    # forward algorithm
    for i in range(1, ell):
        # compute i-th row of DP table
        R = tf.linalg.matvec(A, α[i-1], transpose_a = True)
        α[i].assign(tf.multiply(B[:, y[i]], R))
    return α

def emiProb(α):
    return np.sum(α[-1,:])

In [7]:
α = forward(y)
α.numpy()

array([[0.4    , 0.     , 0.     ],
       [0.112  , 0.064  , 0.036  ],
       [0.04192, 0.0608 , 0.02808]])

In [8]:
Py = emiProb(α)
Py

0.1308

## A HMM as a Special Case of a Recurrent Neural Network
We use the notation of RNNs similar to that in [Dive into Deep Learning](https://d2l.ai/chapter_recurrent-neural-networks/bptt.html). $h_t$ is a size $n$ vector of RNN-"hidden states" (these are real numbers, not to be confused with the hidden states of HMMs, which are from $Q$).  
$$ h_t = f(x_t, h_{t-1}; A, B)$$
We chose the outputs
$$ o_t = \text{sum}(h_t) = h_t[0] + \cdots + h_t[n-1] \in [0,1]$$
so that the final output $o_T$ is just the likelihood of the sequence $P(Y)$.
This RNN does not need to produce intermediate outputs $o_t$ for $t<T$ as they are not used yet. However, they could be used in conjunction with a backwards pass.

### HMMCell
As a template we use the code for [tf.keras.layers.SimpleRNNCell](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/layers/recurrent.py#L1222-L1420)

In [9]:
from HMMCell import HMMCell

## Test the HMM cell

In [10]:
print (f"n={n}, s={s}")

A_init = np.array([[7, 2, 1], [3, 5, 2], [2, 6, 2]]) / 10.0
B_init = np.array([[4, 6], [8, 2], [9, 1]]) / 10.0
I_init = np.array([1, 1e-10, 1e-10]) # start with X1=sun (very likely)

# take ln to cancel out the softmax that is applied to obtain a stochastic matrix 
A_init = np.log(A_init)
B_init = np.log(B_init)
I_init = np.log(I_init)

A_initializer = tf.keras.initializers.Constant(A_init)
B_initializer = tf.keras.initializers.Constant(B_init)
I_initializer = tf.keras.initializers.Constant(I_init)

yi = np.array([[1., 0]]).astype(np.float32) # np.random.random([batch_size, s]).astype(np.float32)
states = np.array([[.4, 0, 0]]).astype(np.float32) # np.random.random([batch_size, n]).astype(np.float32)
hmmC = HMMCell(n,
               transition_initializer=A_initializer,
               emission_initializer=B_initializer,
               init_initializer=I_initializer
              )

output = hmmC(yi, [0, states, 0.])
print("output:\n", output[0], "\n")

A = hmmC.A
B = hmmC.B
I = hmmC.I

with np.printoptions(precision=5, suppress=True):
    print("transition matrix A:\n", A.numpy())
    print("emission matrix B:\n", B.numpy())
    print("initial distribution I:\n", I.numpy())


n=3, s=2
output:
 [[<tf.Tensor: shape=(1,), dtype=int8, numpy=array([0], dtype=int8)>, <tf.Tensor: shape=(1, 3), dtype=float32, numpy=array([[0.5283019 , 0.3018868 , 0.16981131]], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([-1.551169], dtype=float32)>]] 

transition matrix A:
 [[0.7 0.2 0.1]
 [0.3 0.5 0.2]
 [0.2 0.6 0.2]]
emission matrix B:
 [[0.4 0.6]
 [0.8 0.2]
 [0.9 0.1]]
initial distribution I:
 [1. 0. 0.]


In [11]:
inputs = np.array([[[1, 0],[1, 0],[1, 0]]]).astype(np.float32)
hmm = tf.keras.layers.RNN(hmmC, return_sequences = True, return_state = True)
  
alpha, _, lastcol, loglik = hmm(inputs)
alpha = alpha[1]

print()
with np.printoptions(precision=5, suppress=True):
    print ("α=\n", alpha.numpy(),
       "\nlast column of forward table:", lastcol.numpy(),
      "\nlog-likelihood=", loglik.numpy())


α=
 [[[1.      0.      0.     ]
  [0.5283  0.30189 0.16981]
  [0.32049 0.46483 0.21468]]] 
last column of forward table: [[0.32049 0.46483 0.21468]] 
log-likelihood= [-2.03409]


### Training

In [12]:
from dishonest_casino import get_casino_dataset
batch_size = 32
ds = get_casino_dataset().repeat().batch(batch_size)

for inputs in ds.take(1):
    pass
#inputs

In [13]:
n=2
dcc = HMMCell(n)
Q = dcc(inputs[:,0,:], [tf.zeros(batch_size, dtype=tf.int8),
                    tf.zeros([batch_size, s], dtype=tf.float32), 
                    tf.zeros(batch_size, dtype=tf.float32)])

In [14]:
# the model
F = tf.keras.layers.RNN(dcc, return_state = True)

In [15]:
def print_pars(cell):
    with np.printoptions(precision=5, suppress=True):
        print("transition matrix A:\n", cell.A.numpy())
        print("emission matrix B:\n", cell.B.numpy())
        print("initial distribution I:\n", cell.I.numpy())

In [16]:
print_pars(dcc)

transition matrix A:
 [[0.51063 0.48937]
 [0.50921 0.49079]]
emission matrix B:
 [[0.16128 0.17067 0.1652  0.1615  0.173   0.16834]
 [0.17033 0.1675  0.17213 0.16528 0.16311 0.16166]]
initial distribution I:
 [0.5 0.5]


In [17]:
def loss(model, y):
  alpha, _, lastcol, loglik = model(y)
  L = -tf.reduce_mean(loglik)
  return L

L = loss(F, inputs)
#print(f"likelihoods = {lik}\nloss (avg neg log lik)= {loss}")
print("Loss test: {}".format(L))

Loss test: 53.78004455566406


In [18]:
def grad(model, inputs):
  with tf.GradientTape() as tape:
    loss_value = loss(model, inputs)
  return loss_value, tape.gradient(loss_value, model.trainable_variables)

In [19]:
opt = tf.keras.optimizers.Adam(learning_rate=0.01)

In [20]:
model = F
loss_value, grads = grad(model, inputs)

print("Step: {}, Initial Loss: {}".format(opt.iterations.numpy(),
                                          loss_value.numpy()))


Step: 0, Initial Loss: 53.78004455566406


In [21]:
# Keep results for plotting
train_loss_results = []

num_epochs = 41
m = 32 # training batches

for epoch in range(num_epochs):
  epoch_loss_avg = tf.keras.metrics.Mean()
  epoch_accuracy = tf.keras.metrics.SparseCategoricalAccuracy()

  # Training loop - using batches
  for y in ds.take(m):
    # Optimize the model
    loss_value, grads = grad(model, y)
    opt.apply_gradients(zip(grads, model.trainable_variables))

    # Track progress
    epoch_loss_avg.update_state(loss_value)  # Add current batch loss

    # End epoch
  train_loss_results.append(epoch_loss_avg.result())

  if epoch % 2 == 0:
    print("Epoch {:03d}: Loss: {:.3f}".format(epoch, epoch_loss_avg.result()))
  if epoch % 10 == 0:
    print_pars(dcc)

Epoch 000: Loss: 53.444
transition matrix A:
 [[0.61434 0.38566]
 [0.60819 0.39181]]
emission matrix B:
 [[0.15159 0.15244 0.14824 0.15349 0.15701 0.23724]
 [0.16133 0.14995 0.15482 0.1582  0.14968 0.22602]]
initial distribution I:
 [0.55803 0.44197]
Epoch 001: Loss: 53.256
Epoch 002: Loss: 53.262
Epoch 003: Loss: 53.253
Epoch 004: Loss: 53.228
Epoch 005: Loss: 53.230
Epoch 006: Loss: 53.319
Epoch 007: Loss: 53.178
Epoch 008: Loss: 53.169
Epoch 009: Loss: 53.227
Epoch 010: Loss: 53.086
transition matrix A:
 [[0.90121 0.09879]
 [0.10872 0.89128]]
emission matrix B:
 [[0.12209 0.12936 0.1255  0.12569 0.12347 0.3739 ]
 [0.17667 0.1783  0.16655 0.17191 0.17204 0.13453]]
initial distribution I:
 [0.06608 0.93392]
Epoch 011: Loss: 53.159
Epoch 012: Loss: 53.140
Epoch 013: Loss: 53.030
Epoch 014: Loss: 53.058
Epoch 015: Loss: 53.088
Epoch 016: Loss: 53.191
Epoch 017: Loss: 53.120
Epoch 018: Loss: 53.072
Epoch 019: Loss: 52.982
Epoch 020: Loss: 53.096
transition matrix A:
 [[0.86883 0.13117]
 

KeyboardInterrupt: 

In [ ]:
print_pars(dcc)

In [ ]:
L = loss(F, inputs)

In [ ]:
L